# Generated by Django 5.1.3 on 2024-12-08 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('learner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=200, unique=True)),
                ('password', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('preparing_for', models.TextField()),
                ('learner_since', models.DateTimeField()),
            ],
            options={
                'db_table': 'learners',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DomainsInterested',
            fields=[
                ('main_pk', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.TextField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.learners')),
            ],
            options={
                'db_table': 'domains_interested',
                'managed': True,
                'unique_together': {('learner', 'domain_name')},
            },
        ),
    ]
