# Generated by Django 5.1.3 on 2024-12-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpPlatforms',
            fields=[
                ('cp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cp_platform_name', models.CharField(max_length=50)),
                ('cp_url', models.TextField()),
                ('cp_logo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cp_platforms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('short_description', models.TextField(blank=True, null=True)),
                ('parent_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='learners.topics')),
            ],
            options={
                'db_table': 'topics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LearnerCpAccCreds',
            fields=[
                ('main_pk', models.AutoField(primary_key=True, serialize=False)),
                ('cp_platform_name', models.CharField(max_length=50)),
                ('cp_username', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.cpplatforms')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.learners')),
            ],
            options={
                'db_table': 'learner_cp_acc_creds',
                'managed': True,
                'unique_together': {('learner', 'cp')},
            },
        ),
        migrations.CreateModel(
            name='StrongWeakTopics',
            fields=[
                ('main_pk', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(max_length=50)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.learners')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.topics')),
            ],
            options={
                'db_table': 'strong_weak_topics',
                'managed': True,
                'unique_together': {('learner', 'topic')},
            },
        ),
    ]
