# Generated by Django 5.1.3 on 2024-12-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_cpplatforms_topics_learnercpacccreds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='learner_since',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
