# Generated by Django 5.1.3 on 2024-12-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0003_alter_learners_learner_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnercpacccreds',
            name='is_verified',
        ),
    ]
