# Generated by Django 5.1.3 on 2024-12-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0004_remove_learnercpacccreds_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='created_at',
        ),
    ]
