# Generated by Django 5.1.3 on 2024-12-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0005_remove_topics_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learners',
            old_name='name',
            new_name='user',
        ),
    ]
