# Generated by Django 5.1.3 on 2024-12-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0006_rename_name_learners_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learners',
            name='password',
        ),
    ]
