# Generated by Django 5.1.3 on 2024-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0007_remove_learners_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='preparing_for',
            field=models.CharField(choices=[('Intern', 'Internship'), ('Job', 'Full Time')]),
        ),
    ]
