# Generated by Django 5.1.3 on 2024-12-16 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0008_alter_learners_preparing_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercpacccreds',
            name='last_synced',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='learnercpacccreds',
            name='progress',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='learners',
            name='preparing_for',
            field=models.CharField(choices=[('Intern', 'Internship'), ('Job', 'Full Time')], default='Job'),
        ),
    ]
