# Generated by Django 5.1.3 on 2024-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0009_alter_learnercpacccreds_last_synced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercpacccreds',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
