# Generated by Django 5.1.3 on 2024-12-16 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0010_alter_learnercpacccreds_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercpacccreds',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.cpplatforms'),
        ),
        migrations.AlterField(
            model_name='learnercpacccreds',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.learners'),
        ),
    ]
