# Generated by Django 5.1.3 on 2024-12-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0011_alter_learnercpacccreds_cp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strongweaktopics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='strongweaktopics',
            name='topic_name',
            field=models.CharField(default='Unknown'),
        ),
        migrations.RemoveField(
            model_name='strongweaktopics',
            name='topic',
        ),
    ]
