# Generated by Django 5.1.3 on 2024-12-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0013_alter_learners_user_problemscatalog_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
