# Generated by Django 5.1.3 on 2024-12-25 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0016_alter_learners_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learners',
            name='user_name',
            field=models.CharField(default='Paul', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learners',
            name='learner_id',
            field=models.AutoField(default='Paul', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learners',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
