# Generated by Django 5.1.3 on 2024-12-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0017_learners_user_name_alter_learners_learner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='learner_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
