# Generated by Django 5.1.3 on 2024-12-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0018_alter_learners_learner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learners',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='learners',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
