# Generated by Django 5.1.3 on 2024-12-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0019_remove_learners_user_name_alter_learners_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercpacccreds',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
