# Generated by Django 5.1.3 on 2024-12-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0020_alter_learnercpacccreds_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemscatalog',
            name='platform',
        ),
        migrations.DeleteModel(
            name='Problems',
        ),
        migrations.DeleteModel(
            name='ProblemsCatalog',
        ),
    ]
