# Generated by Django 5.1.3 on 2024-12-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0021_remove_problemscatalog_platform_delete_problems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsCatalog',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_name', models.TextField()),
                ('difficulty', models.TextField()),
                ('problem_url', models.TextField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.cpplatforms')),
            ],
            options={
                'db_table': 'problems_catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('main_pk', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_status', models.TextField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.learners')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.problemscatalog')),
            ],
            options={
                'db_table': 'problems',
                'managed': True,
                'unique_together': {('learner', 'problem')},
            },
        ),
    ]
