# Generated by Django 5.1.3 on 2025-01-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0022_problemscatalog_problems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learners',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='cpplatforms',
            name='cp_logo_url',
        ),
        migrations.AddField(
            model_name='cpplatforms',
            name='cp_tot_no_of_quest',
            field=models.IntegerField(default=0),
        ),
    ]
