# Generated by Django 5.1.3 on 2025-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0023_rename_user_learners_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpplatforms',
            name='cp_platform_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
