# Generated by Django 5.1.3 on 2025-01-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0024_alter_cpplatforms_cp_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='bookmarked_status',
            field=models.BooleanField(default=False),
        ),
    ]
