# Generated by Django 5.1.3 on 2025-01-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0025_problems_bookmarked_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_type', models.TextField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily')),
                ('goal_description', models.TextField()),
                ('goal_start', models.DateField()),
                ('goal_end', models.DateField()),
                ('goal_is_active', models.BooleanField(default=True)),
                ('learner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.learners')),
            ],
            options={
                'db_table': 'goals',
                'managed': True,
            },
        ),
    ]
