# Generated by Django 5.1.5 on 2025-01-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0026_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('study_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_group_name', models.CharField(max_length=255)),
                ('meet_link_url', models.URLField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('topics_focused_on', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
                ('learners', models.ManyToManyField(related_name='study_groups', to='learners.learners')),
            ],
        ),
    ]
