# Generated by Django 5.1.5 on 2025-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0027_studygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='learners',
            name='inStudyGroup',
            field=models.BooleanField(default=False),
        ),
    ]
