# Generated by Django 5.1.5 on 2025-01-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0028_learners_instudygroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learners',
            old_name='inStudyGroup',
            new_name='in_study_group',
        ),
    ]
