# Generated by Django 5.1.3 on 2025-01-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0026_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_author', models.CharField(max_length=50)),
                ('blog_created_at', models.DateTimeField()),
                ('blog_title', models.TextField()),
                ('blog_url', models.TextField()),
                ('status', models.BooleanField()),
                ('views_likes', models.IntegerField(blank=True, null=True)),
                ('review_status', models.BooleanField()),
                ('description', models.TextField()),
                ('blog_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learners.topics')),
            ],
            options={
                'db_table': 'blogs',
                'managed': True,
            },
        ),
    ]
