# Generated by Django 5.1.3 on 2025-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_url',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='status',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
