# Generated by Django 5.1.3 on 2025-01-09 15:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_remove_blogs_blog_url_remove_blogs_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='description',
        ),
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Default content'),
        ),
    ]
