# Generated by Django 5.1.3 on 2025-01-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_remove_blogs_description_blogs_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={},
        ),
    ]
