# Generated by Django 5.1.3 on 2025-01-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_alter_blogs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'managed': True},
        ),
    ]
