# Generated by Django 5.1.3 on 2025-01-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_alter_blogs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='review_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='views_likes',
            field=models.IntegerField(default=0),
        ),
    ]
