# Generated by Django 5.1.3 on 2025-01-19 02:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0006_alter_blogs_review_status_alter_blogs_views_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
