# Generated by Django 5.1.3 on 2025-01-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_alter_blogs_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_title',
            field=models.CharField(max_length=50),
        ),
    ]
