# Generated by Django 5.1.5 on 2025-01-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0008_alter_blogs_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.TextField(default='Describe'),
        ),
    ]
