# Generated by Django 5.1.5 on 2025-01-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0009_blogs_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='views_likes',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_url',
            field=models.URLField(default='link'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
