# Generated by Django 5.1.5 on 2025-01-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0010_rename_views_likes_blogs_likes_blogs_blog_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_topic',
            new_name='blog_topic_id',
        ),
    ]
