# Generated by Django 5.1.5 on 2025-01-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0011_rename_blog_topic_blogs_blog_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_topic_id',
            new_name='blog_topic',
        ),
    ]
