# Generated by Django 5.1.5 on 2025-02-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0012_rename_blog_topic_id_blogs_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
