# Generated by Django 5.1.5 on 2025-02-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0013_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
